name: Docker in Docker Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: arc-runner-set
    container:
      image: docker:latest
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Docker
        run: |
          docker version
          docker info

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        run: |
          docker build -t myapp:latest .
          docker run --rm myapp:latest test

    volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket