name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build Job with Docker-in-Docker (DinD)
  build:
    runs-on: arc-runner-set
    services:
      docker:
        image: docker:stable-dind
        options: --privileged --host=unix:///var/run/docker.sock  # Ensures the Docker socket is accessible
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          # Check if Docker is running
          docker info

      - name: Build Docker Image
        run: |
          # Build the Docker image
          docker build -t my-image .

      - name: Verify Docker Socket
        run: |
          # Verify the Docker socket inside the container
          ls -l /var/run/docker.sock

      - name: Check Docker Version
        run: |
          # Check Docker version
          docker version

      - name: List Running Containers
        run: |
          # List running containers to verify everything is set up correctly
          docker ps

  # Test Job
  test:
    runs-on: arc-runner-set
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run Tests
        run: echo "Running tests..."

  # Lint Job
  lint:
    runs-on: arc-runner-set
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Lint Code
        run: echo "Linting code..."

  # Deploy Job
  deploy:
    runs-on: arc-runner-set
    needs: [build, test, lint]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy Application
        run: echo "Deploying application..."
