name: Docker in Docker Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: arc-runner-set
    # Remove container directive since we'll use the host's Docker
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add Docker client setup
      - name: Set up Docker client
        run: |
          # Install Docker client if not present
          if ! command -v docker &> /dev/null; then
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
          fi
          # Verify Docker installation
          docker version
          docker info

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        run: |
          # Build your Docker image
          docker build -t myapp:latest .
          
          # Run tests in the container
          docker run --rm myapp:latest test

      # Optional: Push to registry
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker push myapp:latest