name: Docker in Docker Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: arc-runner-set
    container:
      image: docker:latest
      env:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_TLS_CERTDIR: ""
      
    services:
      docker:
        image: docker:dind
        env:
          DOCKER_TLS_CERTDIR: ""
        options: >-
          --privileged
        ports:
          - 2375:2375

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Wait for Docker
        run: |
          while ! docker info > /dev/null 2>&1; do
            echo "Waiting for Docker to be ready..."
            sleep 1
          done

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Build and test
        run: |
          # Build your Docker image
          docker build -t myapp:latest .
          
          # Run tests in the container
          docker run --rm myapp:latest test

      # Optional: Push to registry
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: |
          docker push myapp:latest